### ISSUE TITLE
Help Wanted: more test files

### ISSUE THREAD

**Issue by philips** [philips/obsidian-plugin-supernote#1]
I could use some test files from X2 devices and some with text too.

**Comment by isolatedvirus** [comment]
link to test files are here:
https://file.io/nZpssgTjMnT0

There are 5 files total
-4 .note files
-1 .doc file

Files were created using the supernote nomad running Chauvet 3.15.27

'20240303_155152.doc' contains a line of text.
'blank template.note' is just a blank .note
'dot template.note' is a blank note using the 5mm dot background
'blank-2p.note' contains two pages of handwritten text, and demos the available writing tools. This was done using the blank background template, and contains a link to the first page on the second page.
'blank-shapes-and-RTR.note' conains a single page of shapes, patterns, and handwritten text. Headings and keyword highlighting included in file. This file was created using Real Time Recognition (allows export of handwritten notes as text within the nomad), with the blank background template.

If you need anything else, please let me know.

**Comment by philips** [comment]
Thanks! Did you try the plugin too? Did it work?

**Comment by philips** [comment]
Thanks @isolatedvirus I added these to the test suite and see that they currently fail. I will try and fix that! https://github.com/philips/supernote-typescript/tree/nomad

```
  ● smoke › convert a note from a nomad Chauvet 3.15.27 with handwriting recognition to png pages

    TypeError: Cannot read properties of undefined (reading 'alpha')

      201 |     let newColor = encodedColor === -1 ? Color("transparent") : translation[encodedColor]
      202 |     let chunk: Buffer
    > 203 |     if (newColor.alpha() === 0) {
          |                  ^
      204 |       chunk = Buffer.from(new Uint8Array([0, 0, 0, 0]))
      205 |     } else {
      206 |       chunk = Buffer.from(new Uint8Array([...newColor.rgb().array(), ~~(255 * newColor.alpha())]))

      at RattaRLEDecoder.addColorBuffer (src/conversion.ts:203:18)
      at RattaRLEDecoder.decode (src/conversion.ts:176:14)
      at src/conversion.ts:46:34
          at Array.map (<anonymous>)
      at src/conversion.ts:45:8
          at Array.map (<anonymous>)
      at src/conversion.ts:42:16
      at src/conversion.ts:8:71
```

**Comment by philips** [comment]
@isolatedvirus Made a new release that extracts the text and images! 

```
Square
Triangle
Circle
Star
```

![nomad-3 15 27-blank-2p note-0](https://github.com/philips/obsidian-plugin-supernote/assets/33544/65cf4101-5144-41bb-b970-0c4c82689dba)
![nomad-3 15 27-blank-2p note-1](https://github.com/philips/obsidian-plugin-supernote/assets/33544/a198c120-c554-4b06-8101-6a3ef742331a)
![nomad-3 15 27-blank-shapes-and-RTR note-0](https://github.com/philips/obsidian-plugin-supernote/assets/33544/d08568d8-25ea-4ab9-acf7-9ea44a644079)

**Comment by orhoncan** [comment]
Hi,
I tried Obsidian importing with this note:
https://file.io/fN9NqG5QRohV

which looks like this in Obsidian:
<img width="653" alt="image" src="https://github.com/philips/obsidian-plugin-supernote/assets/66990865/4e08d78e-f760-42d2-a236-17a6d06b0fe9">

which is fine in Nomad: 
![IMG_6660](https://github.com/philips/obsidian-plugin-supernote/assets/66990865/ec5cb5dd-ff6d-4ae4-8cad-1a669d87204a)

**Comment by jeff-feinsmith** [comment]
Very simple realtime note that is failing on 1.0.2.  SN is A5X with 2.14.28. Obsidian is running on Windows 11 Home, v 23H2, Build 22631.3235.  


 
[20240304_154111 Obsidian Integration Test File.zip](https://github.com/philips/obsidian-plugin-supernote/files/14499269/20240
![20240305_124623](https://github.com/philips/obsidian-plugin-supernote/assets/29148183/d0b32595-420c-41ef-a6fc-e80aa917dab1)
304_154111.Obsidian.Integration.Test.File.zip)

**Comment by philips** [comment]
@orhoncan made a fix! https://github.com/philips/supernote-typescript/commit/990230c8c1c6849f306a2f761557e98afc1b1bec

I want to figure out @Zevoros-cyber issue before cutting a new plugin release.

**Comment by Zevoros-cyber** [comment]
@philips , would you like a complex A5X test file?  I can create one with various styles of links, headings, and keywords if you don't already have one to work with.

**Comment by philips** [comment]
@Zevoros-cyber This is the first time I have had a file with a custom background. I got it to work, I think.

![a5x-2 14 28 note-0](https://github.com/philips/obsidian-plugin-supernote/assets/33544/77707435-461e-4fa9-8cb9-106e24caa82e)

**Comment by isolatedvirus** [comment]
I believe one of the test files I sent over also had a similar issue, but I
think light grey and dark grey were swapped.
answer
On mobile currently so I'm unable to check.

**Comment by philips** [comment]
I uploaded 1.0.3 with fixes for your issues @Zevoros-cyber and @orhoncan. Please give it a try! 

https://github.com/philips/obsidian-plugin-supernote/releases/tag/1.0.3

**Comment by philips** [comment]
@isolatedvirus that is odd.... I filed a bug about the general grayscale handling in the library here: https://github.com/philips/supernote-typescript/issues/1

**Comment by Zevoros-cyber** [comment]
> I uploaded 1.0.3 with fixes for your issues @Zevoros-cyber and @orhoncan. Please give it a try!
> 
> https://github.com/philips/obsidian-plugin-supernote/releases/tag/1.0.3

It's working perfectly!  Of course, with my usually poor handwriting, I'm going to need to automate text cleanup in the md via a local gen AI model.  I think that there should be plugins for that.

**Comment by philips** [comment]
Noice! Thanks for testing @Zevoros-cyber

**Comment by philips** [comment]
I feel pretty good about the test file coverage I have now. Closing.
